from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='CandidateProfile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=200)),('email',models.EmailField(blank=True,max_length=254)),('target_roles',models.JSONField(default=list)),('preferred_locations',models.JSONField(default=list)),('skills',models.JSONField(default=list)),('summary',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Job',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('external_id',models.CharField(max_length=300,unique=True)),('source',models.CharField(max_length=80)),('company',models.CharField(max_length=200)),('title',models.CharField(max_length=300)),('location',models.CharField(blank=True,max_length=300)),('url',models.URLField(max_length=1000)),('description',models.TextField()),('required_skills',models.JSONField(default=list)),('preferred_skills',models.JSONField(default=list)),('experience',models.CharField(blank=True,max_length=100)),('discovered_at',models.DateTimeField(auto_now_add=True)),('posted_at',models.DateTimeField(blank=True,null=True))]),
        migrations.CreateModel(name='Resume',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('file',models.FileField(upload_to='resumes/')),('extracted_text',models.TextField(blank=True)),('uploaded_at',models.DateTimeField(auto_now_add=True)),('profile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='resumes',to='jobs.candidateprofile'))]),
        migrations.CreateModel(name='JobMatch',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('score',models.FloatField()),('skill_match',models.FloatField()),('experience_match',models.FloatField()),('seniority_match',models.FloatField()),('preference_match',models.FloatField()),('matching_skills',models.JSONField(default=list)),('missing_skills',models.JSONField(default=list)),('explanation',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now=True)),('job',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='matches',to='jobs.job')),('profile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='job_matches',to='jobs.candidateprofile'))]),
        migrations.CreateModel(name='Application',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('saved','Saved'),('interested','Interested'),('applied','Applied'),('assessment','Assessment'),('interview','Interview'),('offer','Offer'),('rejected','Rejected'),('withdrawn','Withdrawn')],default='saved',max_length=30)),('resume_suggestions',models.JSONField(default=list)),('cover_letter',models.TextField(blank=True)),('interview_questions',models.JSONField(default=list)),('notes',models.TextField(blank=True)),('applied_at',models.DateTimeField(blank=True,null=True)),('updated_at',models.DateTimeField(auto_now=True)),('job',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='applications',to='jobs.job')),('profile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='applications',to='jobs.candidateprofile'))]),
        migrations.CreateModel(name='Notification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=300)),('message',models.TextField()),('read',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('job',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='jobs.job')),('profile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='notifications',to='jobs.candidateprofile'))]),
        migrations.AlterUniqueTogether(name='jobmatch',unique_together={('job','profile')}),
    ]
