# Generated by Django 5.2.17 on 2026-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_interview_qa_assistantmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_mnc',
            field=models.BooleanField(default=False),
        ),
    ]
